### ISSUE TITLE
Workers invoked via push queues can't be found in test, work fine in dev/prod.

### ISSUE THREAD

**Issue by venantius** [golang/appengine#134]
I've noticed that my task workers never run in tests, and there's an almost complete de-coupling of enqueue/dequeue logic in testing that prevents me from even verifying that the task was properly enqueued. 

Consider the following minimal example:

app.yaml:
```yaml
runtime: go
api_version: go1

handlers:
 - url: /worker/.*
   script: _go_app
   login: admin
 - url: /.*
   script: _go_app
```

```go
package worker

func SettleWorker(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)
	log.Infof(ctx, "Worker was successfully invoked")
}
```

```go
package service

func TestHandler(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)
	t := taskqueue.NewPOSTTask("/worker/wrongpath", map[string][]string{"name": {"BLAH"}})
	task, err := taskqueue.Add(ctx, t, "")
	if err != nil {
		http.Error(w, "Error", http.StatusBadRequest)
		return
	}
	log.Infof(ctx, "Successfully posted task to worker: %+v", task)
}

func init() {
	http.HandleFunc("/worker/settle", worker.SettleWorker)
	http.HandleFunc("/test", TestHandler)
}
```

```go
package service_test

func TestTestHandler(t *testing.T) {
	inst, err := aetest.NewInstance(nil)
	if err != nil {
		t.Fatal(err.Error())
	}
	req, err := inst.NewRequest("GET", "/", nil)
	if err != nil {
		t.Fatal(err.Error())
	}
	resp := httptest.NewRecorder()
	http.HandlerFunc(service.TestHandler).ServeHTTP(resp, req)
}
```

Note that the path being passed to `taskqueue.Add` isn't a valid path. This causes no errors when I test this using `goapp test bitwyrm/service -v` - I see the happy logging statement and a status code of 200 is returned from TestHandler. The logging statement from SettleWorker does not appear. The same thing happens if the path is correct. 

In both cases, there's logging output that suggests that the taskqueue stub is failing to actually find the worker endpoint:

```
INFO     2018-05-03 09:51:11,794 module.py:846] default: "POST /worker/settle HTTP/1.1" 404 19
WARNING  2018-05-03 09:51:11,794 taskqueue_stub.py:2149] Task � failed to execute. This task will retry in 0.100 seconds
INFO     2018-05-03 09:51:11,897 module.py:846] default: "POST /worker/settle HTTP/1.1" 404 19
WARNING  2018-05-03 09:51:11,897 taskqueue_stub.py:2149] Task � failed to execute. This task will retry in 0.200 seconds
INFO     2018-05-03 09:51:12,101 module.py:846] default: "POST /worker/settle HTTP/1.1" 404 19
WARNING  2018-05-03 09:51:12,101 taskqueue_stub.py:2149] Task � failed to execute. This task will retry in 0.400 seconds
```

When I run this outside of test using `dev_appserver.py`, the correct path does trigger the worker, and the incorrect path triggers 403 responses with a series of retries (both behaviors you'd expect). 

Why is this behavior happening? As far as I know this is a behavior that is unique to Go - are other App Engine Standard runtimes are able to find the relevant task queue workers when testing?

In any event, this behavior is frustrating - ideally we'd be able to run tests that actually trigger task workers in order to test a given workflow end-to-end.

**Comment by venantius** [comment]
Oh, to add to this - for some reason running this test also leaves an orphaned `dev_appserver.py` process. Running this repeatedly eventually fills up my computer with orphaned test processes, which in turn cause the dev server to run into database locking issues, meaning I can't run my test suite without manually killing all of the orphaned test processes. Typical stacktrace:

```
...successful test output...
INFO     2018-05-04 09:02:10,762 stub_util.py:357] Applying all pending transactions and saving the datastore
INFO     2018-05-04 09:02:13,827 stub_util.py:360] Saving search indexes
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ursa/Code/google-cloud-sdk/platform/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py", line 2182, in MainLoop
    self._ProcessQueues()
  File "/Users/ursa/Code/google-cloud-sdk/platform/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py", line 2127, in _ProcessQueues
    response_code = self.task_executor.ExecuteTask(task, queue)
  File "/Users/ursa/Code/google-cloud-sdk/platform/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py", line 2059, in ExecuteTask
    '0.1.0.2')
  File "/Users/ursa/Code/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/dispatcher.py", line 776, in add_request
    inst)
  File "/Users/ursa/Code/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/dispatcher.py", line 862, in _handle_request
    request_type=request_type)
  File "/Users/ursa/Code/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/module.py", line 818, in _handle_request
    module=self._module_configuration.module_name)
  File "/Users/ursa/Code/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub.py", line 186, in WrappedMethod
    return method(self, *args, **kwargs)
  File "/Users/ursa/Code/google-cloud-sdk/platform/google_appengine/google/appengine/api/logservice/logservice_stub.py", line 181, in start_request
    host, start_time, method, resource, http_version, module))
OperationalError: database is locked
```

Output of `ps aux`:

```
ursa@leviathan:~/Code/go/src/bitwyrm on (orderbook)
▸ ps aux | grep appengine
ursa              9053   0.0  0.0  4267752    876 s001  S+   12:07pm   0:00.00 grep --color=auto appengine
ursa              8989   0.0  0.0 558436600   3156 s000  S    12:04pm   0:00.00 /var/folders/cx/hmdwt07x6718r3dgxhd3j_q00000gn/T/tmpVICTm2appengine-go-bin/_go_app
ursa              8973   0.0  0.4  4382620  68388 s000  S    12:04pm   0:00.63 /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/ursa/Code/google-cloud-sdk/platform/google_appengine/dev_appserver.py --port=0 --api_port=0 --admin_port=0 --automatic_restart=false --skip_sdk_update_check=true --clear_datastore=true --clear_search_indexes=true --datastore_path /var/folders/cx/hmdwt07x6718r3dgxhd3j_q00000gn/T/appengine-aetest874233379/datastore /var/folders/cx/hmdwt07x6718r3dgxhd3j_q00000gn/T/appengine-aetest874233379
ursa              8711   0.0  0.0 558438264   3596 s000  S    12:04pm   0:00.01 /var/folders/cx/hmdwt07x6718r3dgxhd3j_q00000gn/T/tmpCUAGqZappengine-go-bin/_go_app
ursa              8710   0.0  0.0 558436600   3192 s000  S    12:04pm   0:00.01 /var/folders/cx/hmdwt07x6718r3dgxhd3j_q00000gn/T/tmpCUAGqZappengine-go-bin/_go_app
ursa              8694   0.0  0.4  4390068  67972 s000  S    12:04pm   0:00.94 /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/ursa/Code/google-cloud-sdk/platform/google_appengine/dev_appserver.py --port=0 --api_port=0 --admin_port=0 --automatic_restart=false --skip_sdk_update_check=true --clear_datastore=true --clear_search_indexes=true --datastore_path /var/folders/cx/hmdwt07x6718r3dgxhd3j_q00000gn/T/appengine-aetest718008696/datastore /var/folders/cx/hmdwt07x6718r3dgxhd3j_q00000gn/T/appengine-aetest718008696
```

**Comment by venantius** [comment]
I've pushed up a small demo repository that you can use to replicate this error locally: https://github.com/venantius/demo
