### ISSUE TITLE
Is dev_appserver compatible with go1.1 ?

### ISSUE THREAD

**Issue by pierre-b** [golang/appengine#188]
Hello guys,

I get the following error when starting the dev_appserver with a go1.11 config:

`INFO     2019-01-23 18:24:08,982 devappserver2.py:278] Skipping SDK update check.`
`INFO     2019-01-23 18:24:09,059 api_server.py:275] Starting API server at: http://localhost:56017`
`INFO     2019-01-23 18:24:09,061 stub_util.py:357] Applying all pending transactions and saving the datastore`
`INFO     2019-01-23 18:24:09,061 stub_util.py:360] Saving search indexes`
`Traceback (most recent call last):`
`  File "/sdk-path/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())`
`  File "/sdk-path/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)`
`  File "/sdk-path/google/appengine/tools/devappserver2/devappserver2.py", line 600, in <module>
    main()`
`  File "/sdk-path/google/appengine/tools/devappserver2/devappserver2.py", line 588, in main
    dev_server.start(options)`
`  File "/sdk-path/google/appengine/tools/devappserver2/devappserver2.py", line 360, in start
    options.api_host, apiserver.port, wsgi_request_info_)`
`  File "/sdk-path/google/appengine/tools/devappserver2/dispatcher.py", line 248, in start
    ssl_port)`
`  File "/sdk-path/google/appengine/tools/devappserver2/dispatcher.py", line 384, in _create_module
    ssl_port=ssl_port)`
`  File "/sdk-path/google/appengine/tools/devappserver2/module.py", line 1309, in __init__
    super(AutoScalingModule, self).__init__(**kwargs)`
`  File "/sdk-path/google/appengine/tools/devappserver2/module.py", line 598, in __init__
    self._module_configuration)`
`  File "/sdk-path/google/appengine/tools/devappserver2/module.py", line 231, in _create_instance_factory
    module_configuration=module_configuration)`
`  File "/sdk-path/google/appengine/tools/devappserver2/go/instance_factory.py", line 137, in __init__
    go_config.enable_debugging)`
`  File "/sdk-path/google/appengine/tools/devappserver2/go/application.py", line 117, in __init__
    ROOT_PATH, goroots.GOROOTS[self._module_configuration.api_version])`
`KeyError: 'go111'`

I really need the **dev_appserver** to inject my env variables, reload on file change, serve over https etc... so it would be a hassle to do a simple `go run main.go`.

App engine go extensions version: 1.9.70

Any ideas to make this work please?

Thanks

**Comment by pierre-b** [comment]
My bad, just figured out the app.yml file was wrong, api_version is deprecated and runtime should be switched to go111.
