### ISSUE TITLE
Unable to start local appengine server on OSX

### ISSUE THREAD

**Issue by code4ghana** [golang/appengine#39]
After upgrading to macOS Sierra, I'm unable to start the local development server.  golang/go/issues/16331 appears to be the culprit.

stack trace: 
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x1a291d31a9c2 pc=0xf0eb]

runtime stack:
runtime.throw(0x497380, 0x2a)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x988540)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x988540, 0x1, 0x12, 0xc0d510)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc820035e58)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x988540, 0x1, 0x10000000012, 0xed8f)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x989ff0, 0x0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x989ff0, 0xc820047930)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0xafa960, 0xc800000012, 0xc8209a2fc8)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820012000)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/asm_amd64.s:245 fp=0xc8209a2cc0 sp=0xc8209a2cb8
runtime.mallocgc(0x120, 0x42e320, 0x0, 0x0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/malloc.go:643 +0x869 fp=0xc8209a2d98 sp=0xc8209a2cc0
runtime.newobject(0x42e320, 0xc8209ffd40)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/malloc.go:781 +0x42 fp=0xc8209a2dc0 sp=0xc8209a2d98
cmd/compile/internal/gc.Prog(0x11, 0x0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/gsubr.go:117 +0x58 fp=0xc8209a2e28 sp=0xc8209a2dc0
cmd/compile/internal/amd64.gins(0x11, 0x0, 0xc820665680, 0x0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/amd64/gsubr.go:636 +0xf6 fp=0xc8209a2f08 sp=0xc8209a2e28
cmd/compile/internal/gc.gvardefx(0xc820665680, 0x11)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/pgen.go:100 +0x23a fp=0xc8209a2f98 sp=0xc8209a2f08
cmd/compile/internal/gc.Gvardef(0xc820665680)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/pgen.go:106 +0x2a fp=0xc8209a2fb0 sp=0xc8209a2f98
cmd/compile/internal/gc.componentgen_wb.func2()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/gen.go:1033 +0x3c fp=0xc8209a2fc0 sp=0xc8209a2fb0
cmd/compile/internal/gc.componentgen_wb(0xc8204fe5a0, 0xc820665680, 0xc81ffcd000, 0x0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/gen.go:1129 +0x98c fp=0xc8209a3138 sp=0xc8209a2fc0
cmd/compile/internal/gc.sgen_wb(0xc8204fe5a0, 0xc820665680, 0x10, 0xafa900)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/cgen.go:2274 +0x459 fp=0xc8209a3230 sp=0xc8209a3138
cmd/compile/internal/gc.cgen_wb(0xc8204fe5a0, 0xc820665680, 0x0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/cgen.go:85 +0x427 fp=0xc8209a3600 sp=0xc8209a3230
cmd/compile/internal/gc.Cgen_as_wb(0xc820665680, 0xc8204fe5a0, 0x0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/gen.go:935 +0x166 fp=0xc8209a3660 sp=0xc8209a3600
cmd/compile/internal/gc.Cgen_as(0xc820665680, 0xc8204fe5a0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/gen.go:886 +0x30 fp=0xc8209a3680 sp=0xc8209a3660
cmd/compile/internal/gc.gen(0xc820661170)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/gen.go:833 +0x191 fp=0xc8209a37d8 sp=0xc8209a3680
cmd/compile/internal/gc.Genlist(0xc8203e3fc0)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/gen.go:215 +0x30 fp=0xc8209a37e8 sp=0xc8209a37d8
cmd/compile/internal/gc.compile(0xc8204fe240)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/pgen.go:484 +0xc02 fp=0xc8209a3a58 sp=0xc8209a37e8
cmd/compile/internal/gc.funccompile(0xc8204fe240)
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/dcl.go:1450 +0x1c0 fp=0xc8209a3ad0 sp=0xc8209a3a58
cmd/compile/internal/gc.Main()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/gc/lex.go:472 +0x2116 fp=0xc8209a3df0 sp=0xc8209a3ad0
cmd/compile/internal/amd64.Main()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/internal/amd64/galign.go:127 +0x58d fp=0xc8209a3e58 sp=0xc8209a3df0
main.main()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/cmd/compile/main.go:32 +0x395 fp=0xc8209a3f30 sp=0xc8209a3e58
runtime.main()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/proc.go:188 +0x2b0 fp=0xc8209a3f80 sp=0xc8209a3f30
runtime.goexit()
	/private/var/folders/9y/ppk2fnqj5lscwqw_l6lhdrx8005bt1/T/appengine/go_appengine/goroot/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8209a3f88 sp=0xc8209a3f80
2016/12/15 02:04:28 go-app-builder: build timing: 68×compile (6.865s total), 0×link (0 total)
2016/12/15 02:04:28 go-app-builder: failed running compile: exit status 2
```

**Comment by adamtanner** [comment]
What version of the SDK are you using? We had to do a recent release to add fix go-app-builder on Sierra so you should make sure that you're using the latest version. :)
